Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2019-08, with the labels that each got.

#225 Add `ChosenDeploymentAlphaLocatorFlow` tests
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  CHANGELOG.md
  ci/test.sh
  gdk.pinned
  workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection.meta
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/ChosenDeploymentAlphaLocatorFlow.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/ChosenDeploymentAlphaLocatorFlow.cs.meta
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/SessionConnectionFlowInitializer.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/SessionConnectionFlowInitializer.cs.meta
  workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerWorkerConnector.cs
  workers/unity/Assets/Fps/Tests.meta
  workers/unity/Assets/Fps/Tests/EditmodeTests.meta
  workers/unity/Assets/Fps/Tests/EditmodeTests/ChosenDeploymentAlphaLocatorFlowTests.cs
  workers/unity/Assets/Fps/Tests/EditmodeTests/ChosenDeploymentAlphaLocatorFlowTests.cs.meta
  workers/unity/Assets/Fps/Tests/EditmodeTests/Fps.EditmodeTests.asmdef
  workers/unity/Assets/Fps/Tests/EditmodeTests/Fps.EditmodeTests.asmdef.meta
Labels: size/XL

#226 FPS & `14.0.1` Worker SDK
  CHANGELOG.md
  gdk.pinned
  spatialos.json
  workers/unity/Assets/Fps/Scripts/Config/FpsEntityTemplates.cs
  workers/unity/Assets/Fps/Scripts/GameLogic/Respawning/RespawnHandler.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/ChosenDeploymentLocatorFlow.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/ChosenDeploymentLocatorFlow.cs.meta
  workers/unity/Assets/Fps/Scripts/SetupLogic/Connection/SessionConnectionFlowInitializer.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerWorkerConnector.cs
  workers/unity/Assets/Fps/Tests/EditmodeTests/ChosenDeploymentLocatorFlowTests.cs
  workers/unity/Assets/Fps/Tests/EditmodeTests/ChosenDeploymentLocatorFlowTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.movement/Behaviours/ServerMovementDriver.cs
  workers/unity/Packages/io.improbable.gdk.standardtypes/Vector3Extensions.cs
  workers/unity/spatialos.SimulatedPlayerCoordinator.worker.json
  workers/unity/spatialos.UnityClient.worker.json
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: jira/no-ticket, size/L

#228 Fix Sim Player Coordinator
  workers/unity/spatialos.SimulatedPlayerCoordinator.worker.json
Labels: jira/no-ticket, size/XS

#229 Unity 2019.2.0f1
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  CHANGELOG.md
  ci/UnityEditorHash.txt
  ci/bootstrap.sh
  ci/shared-ci.pinned
  gdk.pinned
  workers/unity/Assets/Fps/Tests/EditmodeTests/Fps.EditmodeTests.asmdef
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/BurstAotSettings_StandaloneLinux64.json
  workers/unity/ProjectSettings/GraphicsSettings.asset
  workers/unity/ProjectSettings/ProjectSettings.asset
  workers/unity/ProjectSettings/ProjectVersion.txt
Labels: jira/no-ticket, size/M
