Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2019-03, with the labels that each got.

#130 Fixed Development scene terrain and bullets remapping
  workers/unity/Assets/Fps/Scenes/FPS-Development.unity
  workers/unity/Packages/com.improbable.gdk.guns/Behaviours/ShotRenderer.cs
Labels: A: art, A: guns

#137 Clean up worker connectors + make map building deferred over frames
  CHANGELOG.md
  default_launch.json
  workers/unity/Assets/Fps/Scripts/Config/MapBuilder.cs
  workers/unity/Assets/Fps/Scripts/Editor/MapBuilderVisualisationWindow.cs
  workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileEnabler.cs
  workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileTypeCollection.cs
  workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileTypeVolume.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/AndroidWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/ConnectionController.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/GameLogicWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnectorBase.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnectorBase.cs.meta
  workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerCoordinatorWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/WorkerConnectorBase.cs
  workers/unity/Assets/Fps/Scripts/SetupLogic/iOSWorkerConnector.cs
Labels: A: maintenance, T: enhancement

#138 Fix shadow issues
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Blank_M.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Default_M.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Default_N.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Foliage_M.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Glossy_M.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Top_M.png.meta
  workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Variant_M.png.meta
  workers/unity/Assets/Fps/Resources/Prefabs/MobileClient/Authoritative/Player.prefab
  workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/Authoritative/Player.prefab
  workers/unity/Assets/Fps/Scenes/FPS-Development.unity
  workers/unity/ProjectSettings/QualitySettings.asset
Labels: A: art, A: maintenance

#140 Fix mac rendering
  workers/unity/Assets/Fps/Config/PostProcessing/Global Post-processing Profile.asset
  workers/unity/ProjectSettings/GraphicsSettings.asset
Labels: A: art, A: maintenance, T: bug

#142 Include core in iOSWorkerConnector
  workers/unity/Assets/Fps/Scripts/SetupLogic/iOSWorkerConnector.cs
Labels: T: bug

#143 Update packer.config.json
  packer.config.json
Labels: A: maintenance

#147 Bump BK queue ID
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: T: bug

#148 Fix package dependency
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.standardtypes/package.json
Labels: T: bug
