Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2020-02, with the labels that each got.

#248 Remove packer config
  packer.config.json
Labels: jira/no-ticket, size/S

#249 Make iOS build on MacOS instead of Windows
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/premerge.steps.yaml
  ci/bootstrap.sh
  ci/shared-ci.pinned
Labels: jira/no-ticket, size/M

#250 Update release QA script
  ci/launch.sh
  gdk.pinned
Labels: jira/no-ticket, size/XS
