Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2020-08, with the labels that each got.

#288 Updated game code for new API's without View
  gdk.pinned
  workers/unity/Assets/Fps/Scripts/Health/Systems/HealthRegenSystem.cs
  workers/unity/Assets/Fps/Scripts/Movement/Behaviours/ProxyMovementDriver.cs
Labels: jira/no-ticket, size/XS

#287 UTY-2646: new dotnet version
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/shared-ci.pinned
  gdk.pinned
Labels: jira/UTY, size/XS

#291 Upgrade to 2020.1
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  gdk.pinned
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/VersionControlSettings.asset
Labels: jira/no-ticket, size/M

#293 Upgrade to entities 0.14
  gdk.pinned
  workers/unity/Assets/Fps/Scripts/Guns/Systems/ServerShootingSystem.cs
  workers/unity/Assets/Fps/Scripts/Health/Systems/HealthRegenSystem.cs
Labels: jira/no-ticket, size/XS
