Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2020-07, with the labels that each got.

#280 UTY-2607: update linux queues
  .buildkite/premerge.steps.yaml
Labels: jira/UTY, size/XS

#282 Entity representation
  .gitignore
  CHANGELOG.md
  gdk.pinned
  workers/unity/Assets/Config/DeploymentLauncherConfig.asset
  workers/unity/Assets/Fps/Config/ClientPrefabMapping.asset
  workers/unity/Assets/Fps/Config/ClientPrefabMapping.asset.meta
  workers/unity/Assets/Fps/Config/GamelogicPrefabMapping.asset
  workers/unity/Assets/Fps/Config/GamelogicPrefabMapping.asset.meta
  workers/unity/Assets/Fps/Config/MobileClientPrefabMapping.asset
  workers/unity/Assets/Fps/Config/MobileClientPrefabMapping.asset.meta
  workers/unity/Assets/Fps/Config/SimulatedPlayerPrefabMapping.asset
  workers/unity/Assets/Fps/Config/SimulatedPlayerPrefabMapping.asset.meta
  workers/unity/Assets/Fps/Prefabs/Entities.meta
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient.meta
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/Authoritative.meta
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/Authoritative/Player.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/Authoritative/Player.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/NonAuthoritative.meta
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/NonAuthoritative/Player.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/MobileClient/NonAuthoritative/Player.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/SimulatedPlayer.meta
  workers/unity/Assets/Fps/Prefabs/Entities/SimulatedPlayer/SimulatedPlayer.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/SimulatedPlayer/SimulatedPlayer.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/SimulatedPlayer/SimulatedPlayerProxy.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/SimulatedPlayer/SimulatedPlayerProxy.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/Authoritative.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/Authoritative/PlayerOwned.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/Authoritative/PlayerOwned.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/NonAuthoritative.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/NonAuthoritative/Player.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/UnityClient/NonAuthoritative/Player.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityGameLogic.meta
  workers/unity/Assets/Fps/Prefabs/Entities/UnityGameLogic/Player.prefab
  workers/unity/Assets/Fps/Prefabs/Entities/UnityGameLogic/Player.prefab.meta
  workers/unity/Assets/Fps/Prefabs/Workers/ClientWorker.prefab
  workers/unity/Assets/Fps/Prefabs/Workers/GameLogicWorker.prefab
  workers/unity/Assets/Fps/Prefabs/Workers/MobileClientWorker.prefab
  workers/unity/Assets/Fps/Prefabs/Workers/SimulatedPlayerWorker.prefab
  workers/unity/Assets/Fps/Scenes/FPS-Development.unity
  workers/unity/Assets/Fps/Scripts/Config/AdvancedEntityPipeline.cs
  workers/unity/Assets/Fps/Scripts/WorkerConnectors/ClientWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/WorkerConnectors/GameLogicWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/WorkerConnectors/MobileWorkerConnector.cs
  workers/unity/Assets/Fps/Scripts/WorkerConnectors/SimulatedPlayerWorkerConnector.cs
Labels: jira/no-ticket, size/L

#281 UTY-2626: change sdk to 14.6.1
  spatialos.json
Labels: jira/UTY, size/XS

#279 Update buildkite artifact path to only use forward slash
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/launch.sh
Labels: jira/no-ticket, size/XS

#283 UTY-2657: set max agents
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: jira/UTY, size/XS

#285 Update Worker SDK Version to 14.7.0
  CHANGELOG.md
  gdk.pinned
  spatialos.json
Labels: jira/no-ticket, size/XS
