Repository spatialos/gdk-for-unity-fps-starter-project, pull requests merged in 2020-04, with the labels that each got.

#255 fastlane
  fastlane/Matchfile
Labels: jira/no-ticket, size/XS

#265 Unshare Apple ID from fastlane Matchfile
  fastlane/Matchfile
Labels: jira/no-ticket, size/XS

#264 QBI query component filtering
  CHANGELOG.md
  gdk.pinned
  snapshots/cloud.snapshot
  snapshots/default.snapshot
  workers/unity/Assets/Fps/Scripts/Config/FpsEntityTemplates.cs
  workers/unity/Assets/Fps/Scripts/Config/OneTimeInitialisation.cs
  workers/unity/Assets/Fps/Scripts/Health/Systems/HealthRegenSystem.cs
  workers/unity/Assets/Fps/Scripts/Metrics/MetricSendSystem.cs
Labels: jira/no-ticket, size/M

#266 re-pin to latest develop
  CHANGELOG.md
  gdk.pinned
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: jira/no-ticket, size/XS

#268 Remove deprecated network type references
  CHANGELOG.md
  workers/unity/Assets/Fps/Scripts/WorkerConnectors/MobileWorkerConnector.cs
Labels: jira/no-ticket, size/S

#269 Remove unused assets
  CHANGELOG.md
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Blue_Team_Banner.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Blue_Team_Banner.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Blue_Team_Button.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Blue_Team_Button.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Orange_Team_Banner.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Orange_Team_Banner.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Orange_Team_Button.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Orange_Team_Button.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Purple_Team_Banner.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Purple_Team_Banner.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Purple_Team_Button.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Purple_Team_Button.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Red_Team_Banner.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Red_Team_Banner.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Red_Team_Button.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Red_Team_Button.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Enter_Your_Name_Here.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Enter_Your_Name_Here.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Enter_Your_Name_Mobile.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Enter_Your_Name_Mobile.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join_Game.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join_Game.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join_Game_Mobile.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Join_Game_Mobile.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Select_Team_Mobile.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Select_Team_Mobile.png.meta
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Select_Your_Team.png
  workers/unity/Assets/Fps/Art/UI/Textures/UI_T_Text_Select_Your_Team.png.meta
  workers/unity/Assets/Fps/Prefabs/UI/Elements/PlayerNameInput.prefab
  workers/unity/Assets/Fps/Prefabs/UI/Elements/PlayerNameInput.prefab.meta
  workers/unity/Assets/Fps/Prefabs/UI/OnScreenUI.prefab
  workers/unity/Assets/Fps/Prefabs/UI/Row.prefab
  workers/unity/Assets/Fps/Prefabs/UI/Row.prefab.meta
  workers/unity/Assets/Fps/Prefabs/UI/StatusText.prefab
  workers/unity/Assets/Fps/Prefabs/UI/StatusText.prefab.meta
Labels: jira/no-ticket, size/XXL
